use_frameworks!

platform :ios, '9.0'

target 'WymanTestPass_Example' do
  pod 'WymanTestPass', :path => '../'

  target 'WymanTestPass_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
